from pydantic import BaseModel, Field, HttpUrl, EmailStr
from typing import Literal, Optional, List, Dict, Any
from uuid import UUID
from enum import Enum
from datetime import datetime






class NotificationTypeEnum(str, Enum):
	"""
	The here Enum:represents the valid channel(s) of communicating with a receipient
	"""
	EMAIL = "email"
	PUSH = "push"

class NotificationStatusEnum(str, Enum):
	"""
	This here Enum:represents the valid states of each notification
	"""
	DELIVERED = "delivered"
	PENDING = "pending"
	FAILED = "failed"
   





class UserPreference(BaseModel):
	email: bool = Field(True, description="A choice: Do you want to use email?.")
	push: bool = Field(True, description="A choice: Do you want to use push?.")




class UserData(BaseModel):
	"""
	This here Model:represents the dynamic data based by the client for template rendering or subtitution
	"""
	name: str
	link: HttpUrl
	meta: Optional[Dict[str, Any]] = None


class NotificationRequest(BaseModel):
	"""
	This here Model:represents the expected structure from an incoming client request
	"""
	notification_type: NotificationTypeEnum = Field(..., description="The channel desired for delivery, email or push.")
	user_id: UUID = Field(..., description="The unique ID of the recepient user.")
	template_code: str = Field(..., description="The key used to look up the template content.")
	variables: UserData = Field(..., description="The dynamic data, used for subtituting the place holders in the templates")
	request_id: str = Field(..., description="A unique id used for tracing this request through the distributed system.")
	priority: int = Field(..., description="An integer used to determine the severity of the payload.")
	metadata: Optional[Dict[str, Any]] = Field(None, description="Optional fields for tracing or special context.")


class NotificationStatus(BaseModel):
	"""
	This here model:represents the Model for delivery services to update the status of a notification.
	"""
	notification_id: UUID = Field(..., description="The ID generated by the API Gateway for tracking.")
	status: NotificationStatusEnum
	timestamp: Optional[datetime] = None
	error: Optional[str] = Field(None, description="Detailed error message if status is 'failed'.")


class TemplateChannelEnum(str, Enum):
    EMAIL = "email"
    PUSH = "push"

class CreateTemplateRequest(BaseModel):
    """Model for creating templates through API Gateway"""
    template_name: str = Field(..., description="Unique name for the template")
    channel_type: TemplateChannelEnum = Field(..., description="Template type: email or push")
    template_subject: Optional[str] = Field(None, description="Email subject (optional for email templates)")
    template_content: str = Field(..., description="Template content with variables")
    template_variables: Optional[List[str]] = Field(None, description="List of variable names")
    template_language: Optional[str] = Field("en", description="Template language")
    template_version: Optional[int] = Field(1, description="Template version")
    is_active: Optional[bool] = Field(True, description="Whether template is active")